import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./AuthProvider";
import { auth } from "./auth";
import ExpiredTokenCheck from "./ExpiredTokenCheck";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider session={session}>
          <ExpiredTokenCheck>
              {children}
          </ExpiredTokenCheck>
        </AuthProvider>
      </body>
    </html>
  );
}
